# Generated by Django 5.1.5 on 2025-02-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_configurator', '0002_case_installed_coolers_alter_case_cooler_slots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='official_site',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
