# Generated by Django 5.1.5 on 2025-02-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_configurator', '0003_alter_manufacturer_official_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocard',
            name='power_pins',
            field=models.JSONField(null=True),
        ),
    ]
