# Generated by Django 5.1.5 on 2025-02-12 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_configurator', '0005_alter_app_id_alter_case_id_alter_casecooler_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casecooler',
            name='connector_pins',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='casecooler',
            name='link',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='casecooler',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pc_configurator.manufacturer'),
        ),
        migrations.AlterField(
            model_name='casecooler',
            name='modular_joint',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='casecooler',
            name='noise_level',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='casecooler',
            name='size',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='disctype',
            name='interface',
            field=models.CharField(max_length=10),
        ),
    ]
