# Generated by Django 5.1.5 on 2025-02-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_configurator', '0006_alter_casecooler_connector_pins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='power_ratio',
            field=models.PositiveSmallIntegerField(default=80),
        ),
    ]
