# Generated by Django 5.1.5 on 2025-02-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_configurator', '0007_certificate_power_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor',
            name='turbo_freq',
            field=models.IntegerField(null=True),
        ),
    ]
