# Generated by Django 5.1.5 on 2025-02-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_configurator', '0008_alter_processor_turbo_freq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherboard',
            name='bluetooth_ver',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='wifi_ver',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
