# Generated by Django 5.1.5 on 2025-02-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_configurator', '0009_alter_motherboard_bluetooth_ver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocard',
            name='chip',
            field=models.CharField(max_length=64),
        ),
    ]
