# Generated by Django 5.1.5 on 2025-02-19 20:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_configurator', '0010_alter_videocard_chip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='psu_typesize',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None),
        ),
    ]
