# Generated by Django 5.1.5 on 2025-02-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_configurator', '0011_alter_case_psu_typesize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='typesize',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
