# Generated by Django 5.1.5 on 2025-02-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_configurator', '0012_alter_case_typesize'),
    ]

    operations = [
        migrations.AddField(
            model_name='processor',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images/components/processor'),
        ),
    ]
