# Generated by Django 5.1.5 on 2025-03-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_configurator', '0014_alter_processor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor',
            name='image',
            field=models.ImageField(null=True, upload_to='pc_configurator/media/components/processor'),
        ),
    ]
