# Generated by Django 5.1.5 on 2025-03-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_configurator', '0015_alter_processor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='image',
            field=models.ImageField(null=True, upload_to='components/case'),
        ),
        migrations.AddField(
            model_name='casecooler',
            name='image',
            field=models.ImageField(null=True, upload_to='components/casecooler'),
        ),
        migrations.AddField(
            model_name='cooler',
            name='image',
            field=models.ImageField(null=True, upload_to='components/cooler'),
        ),
        migrations.AddField(
            model_name='disc',
            name='image',
            field=models.ImageField(null=True, upload_to='components/disc'),
        ),
        migrations.AddField(
            model_name='memory',
            name='image',
            field=models.ImageField(null=True, upload_to='components/memory'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='image',
            field=models.ImageField(null=True, upload_to='components/motherboard'),
        ),
        migrations.AddField(
            model_name='powersupply',
            name='image',
            field=models.ImageField(null=True, upload_to='components/powersupply'),
        ),
        migrations.AddField(
            model_name='videocard',
            name='image',
            field=models.ImageField(null=True, upload_to='components/videocard'),
        ),
        migrations.AlterField(
            model_name='app',
            name='icon',
            field=models.ImageField(null=True, upload_to='apps'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='icon',
            field=models.ImageField(null=True, upload_to='certificates'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='image',
            field=models.ImageField(null=True, upload_to='components/processor'),
        ),
    ]
