# Generated by Django 4.2.20 on 2025-04-06 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc_configurator', '0016_case_image_casecooler_image_cooler_image_disc_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='min_cpu_cores',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='min_cpu_freq',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='min_cpu_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='min_cpu', to='pc_configurator.processor'),
        ),
        migrations.AlterField(
            model_name='app',
            name='min_gpu_chip',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='app',
            name='min_gpu_volume',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='min_ram_volume',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='rec_cpu_cores',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='rec_cpu_freq',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='rec_cpu_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rec_cpu', to='pc_configurator.processor'),
        ),
        migrations.AlterField(
            model_name='app',
            name='rec_gpu_chip',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='app',
            name='rec_gpu_volume',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='rec_ram_volume',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
