# Generated by Django 4.2.20 on 2025-04-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_configurator', '0017_alter_app_min_cpu_cores_alter_app_min_cpu_freq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='category',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='app',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
