# Generated by Django 4.2.20 on 2025-04-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_configurator', '0018_app_category_app_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='description',
        ),
        migrations.RemoveField(
            model_name='app',
            name='min_cpu_model',
        ),
        migrations.RemoveField(
            model_name='app',
            name='min_gpu_chip',
        ),
        migrations.RemoveField(
            model_name='app',
            name='rec_cpu_model',
        ),
        migrations.RemoveField(
            model_name='app',
            name='rec_gpu_chip',
        ),
        migrations.AddField(
            model_name='app',
            name='min_cpu_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='min_gpu_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='rec_cpu_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='rec_gpu_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
