# Generated by Django 4.2.20 on 2025-05-02 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc_configurator', '0019_remove_app_description_remove_app_min_cpu_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powersupply',
            name='certificate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate', related_query_name='certificate', to='pc_configurator.certificate'),
        ),
    ]
