# Generated by Django 4.2.20 on 2025-05-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_configurator', '0020_alter_powersupply_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='modified',
            field=models.DateTimeField(),
        ),
    ]
