# Generated by Django 4.2.20 on 2025-05-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_configurator', '0021_alter_computer_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='name',
            field=models.CharField(max_length=24),
        ),
    ]
